// <auto-generated />
using System;
using CelsiusProWeatherApp.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CelsiusProWeatherApp.Migrations
{
    [DbContext(typeof(WeatherContext))]
    [Migration("20200914152347_AddedNameAttributeToStations")]
    partial class AddedNameAttributeToStations
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CelsiusProWeatherApp.Entities.Station", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Lat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.ToTable("Stations");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b7eba244-620f-492b-b0de-59683aaa5633"),
                            Lat = "7.47",
                            Lon = "46.98",
                            Name = "Berne - Zollikofen"
                        },
                        new
                        {
                            Id = new Guid("cd59526f-d608-4769-a54a-e1bf394ccef2"),
                            Lat = "6.67",
                            Lon = "46.51",
                            Name = "Pully"
                        },
                        new
                        {
                            Id = new Guid("51ae7adb-db3d-4d6a-8d34-d8645f116aec"),
                            Lat = "8.5667",
                            Lon = "47.3831",
                            Name = "ZUERICH/FLUNTERN"
                        });
                });

            modelBuilder.Entity("CelsiusProWeatherApp.Entities.TimeSeries", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("Date")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("StationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TypeOfIndicator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("StationId");

                    b.ToTable("TimeSeries");
                });

            modelBuilder.Entity("CelsiusProWeatherApp.Entities.TimeSeries", b =>
                {
                    b.HasOne("CelsiusProWeatherApp.Entities.Station", "Station")
                        .WithMany()
                        .HasForeignKey("StationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
